# === Rutas principales ===
input_dir: "input"            # Carpeta donde se leen PDFs a procesar
output_dir: "output"          # Carpeta de salida de PDFs firmados
previews_dir: "previews"      # (opcional) Carpeta de vistas previas

# === Firma (imagen a estampar) ===
signature:
  path: "config/firma.png"    # Ruta relativa o absoluta al archivo de firma
  #scale: 0.35                 # Escala de la imagen (1 = tamaño original)
  #keep_aspect: true           # Mantener proporción

# === Reglas de colocación ===
# Es fundamental declarar estas claves para que el exe NO ignore tu archivo
rules_yaml: rules.yaml        # Se recomienda mantener ambas por compatibilidad
rules_file: rules.yaml

# === Defaults globales (usados si las reglas no especifican algo) ===
x: 420                        # Posición X (píxeles)
y: 120                        # Posición Y (píxeles)
rotation: 0                   # Rotación en grados
keep_aspect: true             # Mantener proporción (override posible en rules.yaml)
#width: 220
#height: 90
#scale: 0.35                   # Escala global, se puede ajustar por regla
#stamp_page_range: "1-"        # Rango de páginas donde aplicar la firma
#page: 1                       # Página por defecto